name: Run workflow
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checking code
        uses: actions/checkout@v4
      - name: Showing files
        run: tree .
  run_job:
    runs-on: self-hosted
    steps:
      - name: Verifying the code
        run: tree .
      - name: Running tests
        run: dotnet test
      - name: Running the code
        run: dotnet run --project ./ConsoleApp1/ConsoleApp1.csproj
  show-properties:
    runs-on: self-hosted
    steps:
      - name: run_id
        run: echo "${{ github.run_id }}"

      - name: Testing env variable
        run: echo "VARIABLE:\ ${{ env.ENV_VARIABLE }}"

      - name: Testing env secret
        run: echo ${{ secrets.ENV_SECRET }} > secret.txt && cat secret.txt
