name: Run workflow
on:
  push:
    branches:
      - "main"
jobs:
  run_job:
    runs-on: self-hosted
    steps:
      - name: Checking out the code
        uses: actions/checkout@v4
      - name: Verifying the code
        run: tree .
      - name: Running tests
        run: dotnet test
      - name: Running the code
        run: dotnet run --project ./ConsoleApp1/ConsoleApp1.csproj
